var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,d,f){a instanceof String&&(a=String(a));for(var g=a.length,c=0;c<g;c++){var k=a[c];if(d.call(f,k,c,a))return{i:c,v:k}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,f){a!=Array.prototype&&a!=Object.prototype&&(a[d]=f.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,d,f,g){if(d){f=$jscomp.global;a=a.split(".");for(g=0;g<a.length-1;g++){var c=a[g];c in f||(f[c]={});f=f[c]}a=a[a.length-1];g=f[a];d=d(g);d!=g&&null!=d&&$jscomp.defineProperty(f,a,{configurable:!0,writable:!0,value:d})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,f){return $jscomp.findInternal(this,a,f).v}},"es6","es3");$jscomp.polyfill("Array.prototype.findIndex",function(a){return a?a:function(a,f){return $jscomp.findInternal(this,a,f).i}},"es6","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.Symbol=function(){var a=0;return function(d){return $jscomp.SYMBOL_PREFIX+(d||"")+a++}}();$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};
$jscomp.arrayIterator=function(a){var d=0;return $jscomp.iteratorPrototype(function(){return d<a.length?{done:!1,value:a[d++]}:{done:!0}})};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};
$jscomp.iteratorFromArray=function(a,d){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var f=0,g={next:function(){if(f<a.length){var c=f++;return{value:d(c,a[c]),done:!1}}g.next=function(){return{done:!0,value:void 0}};return g.next()}};g[Symbol.iterator]=function(){return g};return g};$jscomp.polyfill("Array.prototype.values",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a,f){return f})}},"es8","es3");
$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();var d=a[Symbol.iterator];return d?d.call(a):$jscomp.arrayIterator(a)};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function d(){this.batch_=null}function f(a){return a instanceof c?a:new c(function(b,e){b(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;d.prototype.asyncExecute=function(a){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(a);return this};d.prototype.asyncExecuteBatch_=function(){var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})};var g=$jscomp.global.setTimeout;d.prototype.asyncExecuteFunction=function(a){g(a,
0)};d.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var e=a[b];delete a[b];try{e()}catch(h){this.asyncThrow_(h)}}}this.batch_=null};d.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var c=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(e){b.reject(e)}};c.prototype.createResolveAndReject_=
function(){function a(a){return function(h){e||(e=!0,a.call(b,h))}}var b=this,e=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};c.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof c)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};c.prototype.resolveToNonPromiseObj_=function(a){var b=
void 0;try{b=a.then}catch(e){this.reject_(e);return}"function"==typeof b?this.settleSameAsThenable_(b,a):this.fulfill_(a)};c.prototype.reject_=function(a){this.settle_(2,a)};c.prototype.fulfill_=function(a){this.settle_(1,a)};c.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b|"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};c.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
this.onSettledCallbacks_,b=0;b<a.length;++b)a[b].call(),a[b]=null;this.onSettledCallbacks_=null}};var k=new d;c.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};c.prototype.settleSameAsThenable_=function(a,b){var e=this.createResolveAndReject_();try{a.call(b,e.resolve,e.reject)}catch(h){e.reject(h)}};c.prototype.then=function(a,b){function e(b,a){return"function"==typeof b?function(a){try{h(b(a))}catch(m){l(m)}}:a}var h,l,p=new c(function(b,
a){h=b;l=a});this.callWhenSettled_(e(a,h),e(b,l));return p};c.prototype.catch=function(a){return this.then(void 0,a)};c.prototype.callWhenSettled_=function(a,b){function e(){switch(h.state_){case 1:a(h.result_);break;case 2:b(h.result_);break;default:throw Error("Unexpected state: "+h.state_);}}var h=this;null==this.onSettledCallbacks_?k.asyncExecute(e):this.onSettledCallbacks_.push(function(){k.asyncExecute(e)})};c.resolve=f;c.reject=function(a){return new c(function(b,e){e(a)})};c.race=function(a){return new c(function(b,
e){for(var h=$jscomp.makeIterator(a),l=h.next();!l.done;l=h.next())f(l.value).callWhenSettled_(b,e)})};c.all=function(a){var b=$jscomp.makeIterator(a),e=b.next();return e.done?f([]):new c(function(a,l){function h(b){return function(e){c[b]=e;d--;0==d&&a(c)}}var c=[],d=0;do c.push(void 0),d++,f(e.value).callWhenSettled_(h(c.length-1),l),e=b.next();while(!e.done)})};return c},"es6","es3");
$(function(){if(-1==window.location.href.indexOf("onlyShowFeature\x3dtrue")){var a=$(".bread_banner").attr("sku"),d=$(".M_products").attr("title"),f=$(".M_products").attr("img"),g=$("#compare").attr("compare"),c="",k="";0==$("#main").length&&0<$(".bread_banner").length&&$("div.tab-detail-params").show();0==$("#main").length&&0==$(".bread_banner").length&&$(".tab-small-des").show();Vue.mixin({mounted:function(){var b=$(".tab-ctrl li:visible").data("id");$(".tab-ctrl-cont").find("."+b).show()},methods:{getCnNameAndRemarkId:function(b,
a){return a?b+"\x3csup\x3e"+a+"\x3c/sup\x3e":b},isNotEmptyArray:function(b){return b.some(function(b){return b})},isShowImg:function(b){if(b)return/.*?(jpg|gif|png|bmp)$/.test(b)?b.replace(/.*?(jpg|gif|png|bmp)$/,"\x3cimg  src\x3d"+b+' alt\x3d""\x3e'):b.replace(/\n/g,"\x3cbr/\x3e")},formatSpecData:function(b){var a=[],h=this;if(b&&Array.isArray(b)&&b.length){var l=b.findIndex(function(b){return b&&b.specLevelOnes?b.specLevelOnes:-1});if(0>l)return[];b[l]&&b[l].specLevelOnes&&b[l].specLevelOnes.forEach(function(e,
c){b[l].specLevelOnes[c].specleveltwos&&b[l].specLevelOnes[c].specleveltwos.forEach(function(l,d){a.push({specLevelOne:e.cnName,specLevelOneRemarkId:e.remarkId,specLevelTwo:l.remarkId?l.cnName+"\x3csup\x3e "+l.remarkId+"\x3c/sup\x3e":l.cnName,values:function(b){var a=[],e=/.*?(jpg|gif|png|bmp)$/;b.forEach(function(b){b=b&&b.specLevelOnes&&b.specLevelOnes[c]&&b.specLevelOnes[c].specleveltwos&&b.specLevelOnes[c].specleveltwos[d]&&b.specLevelOnes[c].specleveltwos[d].value;null!=b&&(e.test(b)?a.push(b.replace(e,
"\x3cimg  src\x3d"+b+' alt\x3d""\x3e')):a.push(b.replace(/\n/g,"\x3cbr /\x3e")))});return h.isNotEmptyArray(a)?a:null}(b)})})})}return a=a.filter(function(b){return b.values})},isShowAll:function(b){var a=[];b&&b.forEach(function(b){a.push(b.value)});return this.isNotEmptyArray(a)},formatItem:function(b,a,h){return 0===b?a:h[0>b-1?0:b-1].specLevelOne===h[b].specLevelOne?"":a}}});if(a&&""!=a){$.get(_api.productInformation.getInformation()+"\x26eightD\x3d"+a+"\x26t\x3d"+(new Date).getTime(),function(b){b.result&&
($(".Product_names").text(b.returnData.OutMasterData.cnName),"false"==b.returnData.OutMasterData.isHiddenSpec||void 0===b.returnData.OutMasterData.isHiddenSpec?($(".removeLi").hide(),$(".gallery-compare").hide()):$(".removeLi").show(),f?($(".title .width1212").prepend('\x3cimg class\x3d"left" src\x3d"'+f+'"\x3e'),$(".cpxx_tt").remove()):d&&$(".cpxx_tt").text(d))});var n=new Vue({el:"#accessory",data:{accessoryList:[],accessoryHistoryList:[],comments:[],sku8Dlist:[],getAccessoryFinish:!1,pricelist:[],
memberflag:localStorage.customerGroup},created:function(){this.getAccessory()},mounted:function(){},watch:{getAccessoryFinish:function(){this.getMultiPrice()},accessoryList:function(){var b=this;this.$nextTick(function(){$(".jrc_m .prolink").bind("click",function(){var a=$(this).attr("sku");void 0!==a&&$(this).attr("href",b.gotoPDP(a))})})}},methods:{checkStock:function(b){if(0<this.pricelist.filter(function(a){return a.eightcode==b}).length){var a=this.pricelist.filter(function(a){return a.eightcode==
b})[0].productprice.storestatus,h=this.pricelist.filter(function(a){return a.eightcode==b})[0].productprice.salestatus;return"INSTOCK"==a&&"NORMALSALE"==h?!0:!1}return!1},getMultiPrice:function(){var b=this;return new Promise(function(a,h){cartPromise(_api.search.multipricepromotion(),{eightcodes:b.sku8Dlist,channel:"WEB",basestore:"SS",pval:b.memberflag}).then(function(a){"200"==a.returncode&&(b.pricelist=a.data.productpromotelist)})})},getBlockPrice:function(b){return 0<this.pricelist.filter(function(a){return a.eightcode==
b}).length?this.pricelist.filter(function(a){return a.eightcode==b})[0].productprice.price:""},getAccessory:function(){var b=this;queryAxios(_api.productInformation.getAccy()+"\x26eightD\x3d"+a+"\x26t\x3d"+(new Date).getTime(),{},"GET").then(function(a){if(a.data.returnData.OutProductAccessory&&0!=a.data.returnData.OutProductAccessory.length){for(var e=!1,c=0;c<a.data.returnData.OutProductAccessory.length;c++){for(var d=a.data.returnData.OutProductAccessory[c].outProductAccessoryRef,f=[],g=[],k=0;k<
d.length;k++){if("true"==d[k].history)g.push(d[k]);else{var m=d[k].sku8D;void 0===m&&(m=d[k].fitting8D);b.sku8Dlist.push(m);d[k].link=m;f.push(d[k])}d[k].sku8D&&(e=!0)}0<f.length&&(d={outProductAccessoryRef:[]},d.outProductAccessoryRef=f,d.productAccessoryType=a.data.returnData.OutProductAccessory[c].productAccessoryType,b.accessoryList.push(d));0<g.length&&(d={outProductAccessoryRef:[]},d.outProductAccessoryRef=g,d.productAccessoryType=a.data.returnData.OutProductAccessory[c].productAccessoryType,
b.accessoryHistoryList.push(d))}b.getAccessoryFinish=!0;e&&$(".xxk_li.accy").text("\u517c\u5bb9\u4e3b\u673a");$(".xxk_li.accy").parent().show();"true"==getUrlParam("accessory")&&$(".xxk_li.accy").trigger("click")}b.comments=a.data.returnData.commentList}).catch(function(a){console.log(a)})},setSliderEvent:function(a){$(".jr_title a").siblings().removeClass("jr_act");$(n.$refs.slider).eq(a).addClass("jr_act");a=$(".jr_con").eq(a).offset().top;$("html,body").animate({scrollTop:a})},setCommentsEvent:function(a){if($(a.currentTarget).hasClass("zkbz_c"))$(a.currentTarget).removeClass("zkbz_c"),
$(a.currentTarget).closest(".j_beizhu").animate({height:"52px"});else{$(a.currentTarget).addClass("zkbz_c");a=$(a.currentTarget).closest(".j_beizhu");var b=this.comments;1==b.length?a.find("p").each(function(a,e){var c=$(e).attr("comm");a=b[0].comments.filter(function(a){return a.commentId==c})[0].text;$(e).text(a);$(e).attr("title",a)}):a.find("p").each(function(a,e){var c=$(e).attr("comm"),d=$(e).attr("cat");a=b.filter(function(a){return a.categoryName==d})[0].comments.filter(function(a){return a.commentId==
c})[0].text;$(e).text(a);$(e).attr("title",a)});a.animate({height:"230px"})}},setHistoryEvent:function(a){if(!$(a.currentTarget).hasClass("nolists")){$(a.currentTarget).closest(".onHoverInfoList").find(".onHoverInfo").show();var b=this.comments;$(a.currentTarget).closest(".onHoverInfoList").find(".onHoverInfo p").each(function(a,e){var c=$(e).attr("comm");if(1==b.length)a=b[0].comments.filter(function(a){return a.commentId==c})[0].text;else{var d=$(e).attr("cat");a=b.filter(function(a){return a.categoryName==
d})[0].comments.filter(function(a){return a.commentId==c})[0].text}$(e).text(a);$(e).attr("title",a)})}},setHistoryHideEvent:function(a){$(a.currentTarget).parent("div").css("display","none")}}})}void 0!=g&&(c=g.split(","),k=c.length);a&&""!=a&&""!=k&&0<k&&new Vue({el:"#compare",data:{sku8Ds:c,mainSpecInformation:[],detailSpecInformation:[],skuEnName:[]},created:function(){this._getDetailSpec()},methods:{_getDetailSpec:function(){var a=this;queryGet(_api.productInformation.getDetailSpecCompare()+
"\x26sku8Ds\x3d"+c.join()+"\x26t\x3d"+(new Date).getTime(),function(b){if(b.result){a.skuEnName.push(b.returnData.OutSpecCompare.outMasterData);var e=b.returnData.OutSpecCompare.OutSkuMainSpec;a.detailSpecInformation=a.formatSpecData(b.returnData.OutSpecCompare.OutSkuDetailSpec);a.mainSpecInformation=a.formatSpecData(e);a.$nextTick(function(){(new spec("specs")).init()})}},!0)},ImageClick:function(){$(".cs_zk").css("display","block");$(".zhankai").css("display","none")}}});a&&""!=a&&k&&(new Vue({el:"#DetailSpec",
data:{eightD:a,detailSpecInformation:[],remarks:[],remarksInformationArr:[],otherDescription:""},created:function(){this._getDetailSpec()},methods:{_getDetailSpec:function(){var a=this;queryGet(_api.productInformation.getDetailSpecCompare()+"\x26sku8Ds\x3d"+c.join()+"\x26t\x3d"+(new Date).getTime(),function(b){!0===b.result&&b.returnData.OutSpecCompare.OutSkuDetailSpec&&(a.detailSpecInformation=a.formatSpecData(b.returnData.OutSpecCompare.OutSkuDetailSpec),a.otherDescription=b.returnData.OutSpecCompare.OutSkuDetailSpec[0].otherDescription,
a.remarksInformationArr=b.returnData.OutSpecCompare.OutSkuDetailSpec.map(function(a){return a&&a.remarks?a.remarks:[]}))})},ImageClick:function(){$(".cs_zk").css("display","block");$(".zhankai").css("display","none")}}}),new Vue({el:"#MainSpec",data:{isMoreProduct:!0}}));a&&""!=a&&!k&&(new Vue({el:"#MainSpec",data:{eightD:a,mainSpecInformation:[],isMoreProduct:!1,otherDescription:""},created:function(){this._getMainSpec()},watch:{mainSpecInformation:function(){}},methods:{_getMainSpec:function(){var b=
this;queryGet(_api.productInformation.getMainSpec()+"\x26eightD\x3d"+a+"\x26t\x3d"+(new Date).getTime(),function(a){if(a.result){var c=a.returnData.OutSkuMainSpec.specLevelOnes;b.otherDescription=a.returnData.OutSkuMainSpec.otherDescription;b.mainSpecInformation.push(c)}})}}}),new Vue({el:"#DetailSpec",data:{eightD:a,detailSpecInformation:[],remarks:[],remarksInformationArr:null,otherDescription:""},created:function(){this._getDetailSpec()},methods:{_getDetailSpec:function(){var b=this;queryGet(_api.productInformation.getDetailSpec()+
"\x26eightD\x3d"+a+"\x26t\x3d"+(new Date).getTime(),function(a){if(!0===a.result&&void 0!==a.returnData.OutSkuDetailSpec.specLevelOnes){var c=a.returnData.OutSkuDetailSpec.specLevelOnes,e=a.returnData.OutSkuDetailSpec.remarks;b.otherDescription=a.returnData.OutSkuDetailSpec.otherDescription;b.detailSpecInformation.push(c);b.remarks.push(e)}})},ImageClick:function(){$(".cs_zk").css("display","block");$(".zhankai").css("display","none")},isShowImg:function(a){if(a)return/.*?(jpg|gif|png|bmp)$/.test(a)?
a.replace(/.*?(jpg|gif|png|bmp)$/,"\x3cimg  src\x3d"+a+' alt\x3d""\x3e'):a.replace(/\n/g,"\x3cbr/\x3e")},isShowAll:function(a){var b=[];a.forEach(function(a){b.push(a.value)});return this.isNotEmptyArray(b)},isNotEmptyArray:function(a){return a.some(function(a){return a})}}}));$(".specli").find("li").each(function(b,c){var d=$(this).attr("sku").split(",");if(d&&0<=d.indexOf(a))for($(".Product_Fecture").eq(b).show(),$(this).find("a").addClass("cur"),$.ajaxSettings.async=!1,b=0;b<d.length;b++)$.get(_api.productInformation.getInformation()+
"\x26eightD\x3d"+d[b].trim()+"\x26t\x3d"+(new Date).getTime(),function(c){c.result&&c.returnData.OutMasterData.colorImage&&c.returnData.OutMasterData.color&&(d[b]==a?$(".colorli ul").append('\x3cli sku\x3d"'+d[b]+'"\x3e\x3ca href\x3d"javascript:void(0)" class\x3d"cur"\x3e\x3cspan\x3e\x3cimg src\x3d"'+c.returnData.OutMasterData.colorImage+'" alt\x3d"'+c.returnData.OutMasterData.color+'"\x3e\x3cstrong\x3e'+c.returnData.OutMasterData.color+"\x3c/strong\x3e\x3c/span\x3e\x3c/a\x3e\x3c/li\x3e"):$(".colorli ul").append('\x3cli sku\x3d"'+
d[b]+'"\x3e\x3ca href\x3d"javascript:void(0)"\x3e\x3cspan\x3e\x3cimg src\x3d"'+c.returnData.OutMasterData.colorImage+'" alt\x3d"'+c.returnData.OutMasterData.color+'"\x3e\x3cstrong\x3e'+c.returnData.OutMasterData.color+"\x3c/strong\x3e\x3c/span\x3e\x3c/a\x3e\x3c/li\x3e"))})})}else $(".tab-ctrl li[data-id\x3d'tab-small-des']").trigger("click");g="";0<$(".featureb").length?1==Math.floor(2*Math.random())?($(".featureb").show(),$(".featurea").hide(),g="a"):($(".featurea").show(),$(".featureb").hide(),
g="b"):$(".featurea").show();"undefined"!=typeof s_gi&&(k=s_gi("sonycnstyle"),k.linkTrackVars="eVar71",k.eVar71=galleryab+"/"+g,k.prop71=galleryab+"/"+g,k.tl(this,"o",galleryab+"/"+g))});
