var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,d,c){b!=Array.prototype&&b!=Object.prototype&&(b[d]=c.value)};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var b=0;return function(d){return $jscomp.SYMBOL_PREFIX+(d||"")+b++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var b=$jscomp.global.Symbol.iterator;b||(b=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[b]&&$jscomp.defineProperty(Array.prototype,b,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(b){var d=0;return $jscomp.iteratorPrototype(function(){return d<b.length?{done:!1,value:b[d++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(b){$jscomp.initSymbolIterator();b={next:b};b[$jscomp.global.Symbol.iterator]=function(){return this};return b};$jscomp.makeIterator=function(b){$jscomp.initSymbolIterator();var d=b[Symbol.iterator];return d?d.call(b):$jscomp.arrayIterator(b)};$jscomp.arrayFromIterator=function(b){for(var d,c=[];!(d=b.next()).done;)c.push(d.value);return c};$jscomp.arrayFromIterable=function(b){return b instanceof Array?b:$jscomp.arrayFromIterator($jscomp.makeIterator(b))};
$jscomp.findInternal=function(b,d,c){b instanceof String&&(b=String(b));for(var e=b.length,f=0;f<e;f++){var l=b[f];if(d.call(c,l,f,b))return{i:f,v:l}}return{i:-1,v:void 0}};$jscomp.polyfill=function(b,d,c,e){if(d){c=$jscomp.global;b=b.split(".");for(e=0;e<b.length-1;e++){var f=b[e];f in c||(c[f]={});c=c[f]}b=b[b.length-1];e=c[b];d=d(e);d!=e&&null!=d&&$jscomp.defineProperty(c,b,{configurable:!0,writable:!0,value:d})}};
$jscomp.polyfill("Array.prototype.find",function(b){return b?b:function(b,c){return $jscomp.findInternal(this,b,c).v}},"es6","es3");$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(b){function d(){this.batch_=null}function c(b){return b instanceof f?b:new f(function(c,e){c(b)})}if(b&&!$jscomp.FORCE_POLYFILL_PROMISE)return b;d.prototype.asyncExecute=function(b){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(b);return this};d.prototype.asyncExecuteBatch_=function(){var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})};var e=$jscomp.global.setTimeout;d.prototype.asyncExecuteFunction=function(b){e(b,
0)};d.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var b=this.batch_;this.batch_=[];for(var c=0;c<b.length;++c){var e=b[c];delete b[c];try{e()}catch(n){this.asyncThrow_(n)}}}this.batch_=null};d.prototype.asyncThrow_=function(b){this.asyncExecuteFunction(function(){throw b;})};var f=function(b){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var c=this.createResolveAndReject_();try{b(c.resolve,c.reject)}catch(m){c.reject(m)}};f.prototype.createResolveAndReject_=
function(){function b(b){return function(d){e||(e=!0,b.call(c,d))}}var c=this,e=!1;return{resolve:b(this.resolveTo_),reject:b(this.reject_)}};f.prototype.resolveTo_=function(b){if(b===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(b instanceof f)this.settleSameAsPromise_(b);else{a:switch(typeof b){case "object":var c=null!=b;break a;case "function":c=!0;break a;default:c=!1}c?this.resolveToNonPromiseObj_(b):this.fulfill_(b)}};f.prototype.resolveToNonPromiseObj_=function(b){var c=
void 0;try{c=b.then}catch(m){this.reject_(m);return}"function"==typeof c?this.settleSameAsThenable_(c,b):this.fulfill_(b)};f.prototype.reject_=function(b){this.settle_(2,b)};f.prototype.fulfill_=function(b){this.settle_(1,b)};f.prototype.settle_=function(b,c){if(0!=this.state_)throw Error("Cannot settle("+b+", "+c|"): Promise already settled in state"+this.state_);this.state_=b;this.result_=c;this.executeOnSettledCallbacks_()};f.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var b=
this.onSettledCallbacks_,c=0;c<b.length;++c)b[c].call(),b[c]=null;this.onSettledCallbacks_=null}};var l=new d;f.prototype.settleSameAsPromise_=function(b){var c=this.createResolveAndReject_();b.callWhenSettled_(c.resolve,c.reject)};f.prototype.settleSameAsThenable_=function(b,c){var e=this.createResolveAndReject_();try{b.call(c,e.resolve,e.reject)}catch(n){e.reject(n)}};f.prototype.then=function(b,c){function e(b,c){return"function"==typeof b?function(c){try{d(b(c))}catch(t){k(t)}}:c}var d,k,g=new f(function(b,
c){d=b;k=c});this.callWhenSettled_(e(b,d),e(c,k));return g};f.prototype.catch=function(b){return this.then(void 0,b)};f.prototype.callWhenSettled_=function(b,c){function e(){switch(d.state_){case 1:b(d.result_);break;case 2:c(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?l.asyncExecute(e):this.onSettledCallbacks_.push(function(){l.asyncExecute(e)})};f.resolve=c;f.reject=function(b){return new f(function(c,e){e(b)})};f.race=function(b){return new f(function(e,
d){for(var f=$jscomp.makeIterator(b),m=f.next();!m.done;m=f.next())c(m.value).callWhenSettled_(e,d)})};f.all=function(b){var e=$jscomp.makeIterator(b),d=e.next();return d.done?c([]):new f(function(b,f){function m(c){return function(e){k[c]=e;n--;0==n&&b(k)}}var k=[],n=0;do k.push(void 0),n++,c(d.value).callWhenSettled_(m(k.length-1),f),d=e.next();while(!d.done)})};return f},"es6","es3");
$jscomp.checkEs6ConformanceViaProxy=function(){try{var b={},d=Object.create(new $jscomp.global.Proxy(b,{get:function(c,e,f){return c==b&&"q"==e&&f==d}}));return!0===d.q}catch(c){return!1}};$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS=!1;$jscomp.ES6_CONFORMANCE=$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS&&$jscomp.checkEs6ConformanceViaProxy();$jscomp.owns=function(b,d){return Object.prototype.hasOwnProperty.call(b,d)};
$jscomp.polyfill("WeakMap",function(b){function d(){if(!b||!Object.seal)return!1;try{var c=Object.seal({}),e=Object.seal({}),d=new b([[c,2],[e,3]]);if(2!=d.get(c)||3!=d.get(e))return!1;d.delete(c);d.set(e,4);return!d.has(c)&&4==d.get(e)}catch(q){return!1}}function c(b){$jscomp.owns(b,f)||$jscomp.defineProperty(b,f,{value:{}})}function e(b){var e=Object[b];e&&(Object[b]=function(b){c(b);return e(b)})}if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(b&&$jscomp.ES6_CONFORMANCE)return b}else if(d())return b;
var f="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var l=0,g=function(b){this.id_=(l+=Math.random()+1).toString();if(b){$jscomp.initSymbol();$jscomp.initSymbolIterator();b=$jscomp.makeIterator(b);for(var c;!(c=b.next()).done;)c=c.value,this.set(c[0],c[1])}};g.prototype.set=function(b,e){c(b);if(!$jscomp.owns(b,f))throw Error("WeakMap key fail: "+b);b[f][this.id_]=e;return this};g.prototype.get=function(b){return $jscomp.owns(b,f)?b[f][this.id_]:void 0};g.prototype.has=
function(b){return $jscomp.owns(b,f)&&$jscomp.owns(b[f],this.id_)};g.prototype.delete=function(b){return $jscomp.owns(b,f)&&$jscomp.owns(b[f],this.id_)?delete b[f][this.id_]:!1};return g},"es6","es3");$jscomp.MapEntry=function(){};
$jscomp.polyfill("Map",function(b){function d(){if($jscomp.ASSUME_NO_NATIVE_MAP||!b||"function"!=typeof b||!b.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),e=new b($jscomp.makeIterator([[c,"s"]]));if("s"!=e.get(c)||1!=e.size||e.get({x:4})||e.set({x:4},"t")!=e||2!=e.size)return!1;var d=e.entries(),f=d.next();if(f.done||f.value[0]!=c||"s"!=f.value[1])return!1;f=d.next();return f.done||4!=f.value[0].x||"t"!=f.value[1]||!d.next().done?!1:!0}catch(p){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(b&&$jscomp.ES6_CONFORMANCE)return b}else if(d())return b;$jscomp.initSymbol();$jscomp.initSymbolIterator();var c=new WeakMap,e=function(b){this.data_={};this.head_=g();this.size=0;if(b){b=$jscomp.makeIterator(b);for(var c;!(c=b.next()).done;)c=c.value,this.set(c[0],c[1])}};e.prototype.set=function(b,c){var e=f(this,b);e.list||(e.list=this.data_[e.id]=[]);e.entry?e.entry.value=c:(e.entry={next:this.head_,previous:this.head_.previous,head:this.head_,
key:b,value:c},e.list.push(e.entry),this.head_.previous.next=e.entry,this.head_.previous=e.entry,this.size++);return this};e.prototype.delete=function(b){b=f(this,b);return b.entry&&b.list?(b.list.splice(b.index,1),b.list.length||delete this.data_[b.id],b.entry.previous.next=b.entry.next,b.entry.next.previous=b.entry.previous,b.entry.head=null,this.size--,!0):!1};e.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=g();this.size=0};e.prototype.has=function(b){return!!f(this,b).entry};
e.prototype.get=function(b){return(b=f(this,b).entry)&&b.value};e.prototype.entries=function(){return l(this,function(b){return[b.key,b.value]})};e.prototype.keys=function(){return l(this,function(b){return b.key})};e.prototype.values=function(){return l(this,function(b){return b.value})};e.prototype.forEach=function(b,c){for(var e=this.entries(),d;!(d=e.next()).done;)d=d.value,b.call(c,d[1],d[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var f=function(b,e){var d=e&&typeof e;"object"==
d||"function"==d?c.has(e)?d=c.get(e):(d=""+ ++k,c.set(e,d)):d="p_"+e;var f=b.data_[d];if(f&&$jscomp.owns(b.data_,d))for(b=0;b<f.length;b++){var g=f[b];if(e!==e&&g.key!==g.key||e===g.key)return{id:d,list:f,index:b,entry:g}}return{id:d,list:f,index:-1,entry:void 0}},l=function(b,c){var e=b.head_;return $jscomp.iteratorPrototype(function(){if(e){for(;e.head!=b.head_;)e=e.previous;for(;e.next!=e.head;)return e=e.next,{done:!1,value:c(e)};e=null}return{done:!0,value:void 0}})},g=function(){var b={};return b.previous=
b.next=b.head=b},k=0;return e},"es6","es3");
$jscomp.polyfill("Set",function(b){function d(){if($jscomp.ASSUME_NO_NATIVE_SET||!b||"function"!=typeof b||!b.prototype.entries||"function"!=typeof Object.seal)return!1;try{var e=Object.seal({x:4}),c=new b($jscomp.makeIterator([e]));if(!c.has(e)||1!=c.size||c.add(e)!=c||1!=c.size||c.add({x:4})!=c||2!=c.size)return!1;var d=c.entries(),g=d.next();if(g.done||g.value[0]!=e||g.value[1]!=e)return!1;g=d.next();return g.done||g.value[0]==e||4!=g.value[0].x||g.value[1]!=g.value[0]?!1:d.next().done}catch(k){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(b&&$jscomp.ES6_CONFORMANCE)return b}else if(d())return b;$jscomp.initSymbol();$jscomp.initSymbolIterator();var c=function(b){this.map_=new Map;if(b){b=$jscomp.makeIterator(b);for(var c;!(c=b.next()).done;)this.add(c.value)}this.size=this.map_.size};c.prototype.add=function(b){this.map_.set(b,b);this.size=this.map_.size;return this};c.prototype.delete=function(b){b=this.map_.delete(b);this.size=this.map_.size;return b};c.prototype.clear=function(){this.map_.clear();
this.size=0};c.prototype.has=function(b){return this.map_.has(b)};c.prototype.entries=function(){return this.map_.entries()};c.prototype.values=function(){return this.map_.values()};c.prototype.keys=c.prototype.values;c.prototype[Symbol.iterator]=c.prototype.values;c.prototype.forEach=function(b,c){var e=this;this.map_.forEach(function(d){return b.call(c,d,d,e)})};return c},"es6","es3");var _dtm_addToBasket,_dtm_addWishlistEntry,a={};
$(function(){-1==window.location.href.indexOf("onlyShowFeature\x3dtrue")&&1==$("#price").length&&(new Vue({el:"#main",data:{num:1,sku:$(".bread_banner").attr("sku"),MAX_BUY_NUM:10,price:"",memberPrice:"",memberPriceFlag:"",priceFlag:"",wishListFlag:!1,customerGroup:localStorage.customerGroup,promotionList:[],focList:[],cartFocList:[],hideMorePromotion:!0,pts:"",buyMoreList:[],buyMoreFlag:!1,firedmessage:"",canBuyMore:!0,preSale:!1,preSaleRule:"",preStartDate:"",preEndDate:"",preSalePrice:"",prePayStartDate:"",
prePrice:0,preSaleShow:!1,salestatus:"",storestatus:"",currentDate:"",preButton:"",preSmallButton:"",masterData:"",flashBuy:!1,flashBuyData:{},flashBuyRemainingTime:"",flashStart:"",flashEnd:"",flashPromoStart:"",currentTimeSecond:"",flashflag:0,mtype:"",error:"this.onerror\x3dnull;this.src\x3d'/etc/designs/sonystyle/images/default_gift.jpg'",couponList:[],couponIds:[],couponStatus:[],couponHeight:"",showCoupon:!1,live:{liveStatus:"Finish"},instalmentData:{},instalmentShow:!1,instalmentchecked1:null,
instalmentchecked2:null,recommendInstalment1:null,recommendInstalment2:null,instalmentBGX:null==this.instalmentchecked1?"0px":$(".instalment_item").eq(this.instalmentchecked1).css("width").replace("px","")-148+"px",instalmentPriceFlag:!1,regprice:"",rcmFlag:$(".rcm_con").attr("sku"),rcmType:$(".rcm_con").attr("type"),rcmManualSKU:$(".rcm_con").attr("manualsku"),rcmSKU:[],rcmData:{},rcmMasterData:{},rcmPIMSKU:[],rcmESData:{},rcmScroll:!1},created:function(){var b=this;cartGetPromise(_api.productInformation.getInformation()+
"\x26eightD\x3d"+this.sku).then(function(d){"00"==d.code&&d.result&&(b.masterData=d.returnData.OutMasterData)});this.getCoupon();this.__getCountDownTime().then(function(d){"00"==d.resultMsg[0].code&&(b.currentDate=d.resultData.countDownTime.substr(0,14))});this.getPrice().then(function(d){if(void 0!==b.masterData.flashBuyProduct){b.flashBuyData=b.masterData.flashBuyProduct;var c=b.flashBuyData.startBuy.substr(0,14);b.flashStart=(new Date(c.substring(0,4)+"/"+c.substring(4,6)+"/"+c.substring(6,8)+
" "+c.substring(8,10)+":"+c.substring(10,12)+":"+c.substring(12,14))).getTime();var e=b.flashBuyData.endDate.substr(0,14);b.flashEnd=(new Date(e.substring(0,4)+"/"+e.substring(4,6)+"/"+e.substring(6,8)+" "+e.substring(8,10)+":"+e.substring(10,12)+":"+e.substring(12,14))).getTime();var f=b.flashBuyData.startDate.substr(0,14);b.flashPromoStart=(new Date(f.substring(0,4)+"/"+f.substring(4,6)+"/"+f.substring(6,8)+" "+f.substring(8,10)+":"+f.substring(10,12)+":"+f.substring(12,14))).getTime();b.flashEnd=
(new Date(e.substring(0,4)+"/"+e.substring(4,6)+"/"+e.substring(6,8)+" "+e.substring(8,10)+":"+e.substring(10,12)+":"+e.substring(12,14))).getTime();b.currentTimeSecond=(new Date(b.currentDate.substring(0,4)+"/"+b.currentDate.substring(4,6)+"/"+b.currentDate.substring(6,8)+" "+b.currentDate.substring(8,10)+":"+b.currentDate.substring(10,12)+":"+b.currentDate.substring(12,14))).getTime();b.currentDate>c&&b.currentDate<e&&(b.flashBuyRemainingTime=parseInt(b.flashEnd)-parseInt(b.currentTimeSecond),b.flashflag=
1,b.flashBuy=!0);f<b.currentDate&&b.currentDate<c&&(b.flashBuyRemainingTime=parseInt(b.flashStart)-parseInt(b.currentTimeSecond),b.flashBuy=!0);b.currentDate>e&&(console.log(b.currentDate>e),b.flashBuy=!1);f>b.currentDate&&(b.flashBuyRemainingTime=parseInt(b.flashPromoStart)-parseInt(b.currentTimeSecond),b.flashflag=-1);0<b.flashBuyRemainingTime&&b.remainTimeCountDonw()}else b.mtype=d.data.productprice.mtype,"PRESALES"==d.data.productprice.salestatus&&void 0!==b.masterData.hybris.depositpay?(b.preSale=
!0,600>d.data.productprice.price-b.masterData.hybris.depositpay.amount&&(b.instalmentPriceFlag=!0)):"PRESALES"==d.data.productprice.salestatus&&void 0===b.masterData.hybris.depositpay&&(b.preButton="/etc/designs/sonystyle/images/buybutton/button_presale_big.png",b.preSmallButton="/etc/designs/sonystyle/images/buybutton/button_presale_small.png");1!=b.preSale?600>d.data.productprice.price&&(b.instalmentPriceFlag=!0):600>d.data.productprice.price-b.masterData.hybris.depositpay.amount&&(b.instalmentPriceFlag=
!0)});this.getInstalment().then(function(d){"200"==d.returncode&&(b.instalmentData=d.data,0<b.instalmentData.length&&b.instalmentData.forEach(function(c,e){c=c.providerBanks[0].installmentEntries;0<c.length&&(b.instalmentShow=!0);c.forEach(function(c,d){1==c.isrecommend&&(b.recommendInstalment1=e,b.recommendInstalment2=d)})}))});$(".num_p").find("input").text(this.num);void 0!==localStorage.access_token&&""!=localStorage.access_token&&this.readWishList();this.rcmFlag&&("manual"==this.rcmType&&""!=
this.rcmManualSKU?this.rcmSKU=this.rcmManualSKU.split(","):this.getRcmData(this.sku,this.rcmFlag))},watch:{masterData:function(){var b=this;this.getLiveStatus(void 0!==this.masterData.productModelEnName?this.masterData.productModelEnName:this.masterData.accessoriesModelEnName).then(function(d){"200"==d.returnCode&&(b.live=d.returnData)})},preSale:function(){this.preStartDate=this.masterData.hybris.depositpay.depositPaymentStartDate;this.preEndDate=this.masterData.hybris.depositpay.depositPaymentEndDate;
this.prePayStartDate=this.masterData.hybris.depositpay.depositFullPaymentStartDate;this.prePrice=this.masterData.hybris.depositpay.amount;this.preStartDate<this.currentDate&&this.currentDate<this.preEndDate?(this.preSale=this.preSaleShow=!0,this.preSaleRule=this.masterData.hybris.depositpay.depositRuleDescription,this.preButton="/etc/designs/sonystyle/images/buybutton/button_subscription_big.png",this.preSmallButton="/etc/designs/sonystyle/images/buybutton/button_subscription_small.png"):this.currentDate>
this.preEndDate?(this.preSaleShow=!1,this.preSale=!0,this.preSaleRule=this.masterData.hybris.depositpay.depositRuleDescription):this.currentDate<this.prePayStartDate&&(this.preSale=this.preSaleShow=!0,this.preSaleRule=this.masterData.hybris.depositpay.depositRuleDescription)},couponIds:function(){var b=this;void 0!==localStorage.access_token&&""!==localStorage.access_token&&this._checkCouponStatus().then(function(d){"00"==d.resultMsg[0].code&&(b.couponStatus=d.resultData)})},showCoupon:function(){3<
this.couponList.length&&1==this.showCoupon&&setTimeout(function(){$("#coupons").scrollBar({barWidth:10,position:"y",wheelDis:15,right:20})},300)},instalmentchecked2:function(){var b=this;setTimeout(function(){b.instalmentBGX=null==b.instalmentchecked1?"0px":$(".instalment_item").eq(b.instalmentchecked1).css("width").replace("px","")-138+"px"},10)},rcmSKU:function(){var b=this;cartGetPromise(_api.productInformation.getInformationList()+"\x26sku8Ds\x3d"+this.rcmSKU).then(function(d){d.result&&"00"==
d.code&&0<d.returnData.OutMasterDatas.length&&(b.rcmMasterData=d.returnData.OutMasterDatas,b.rcmData=b.rcmSKU.filter(function(c){return 0<=b.rcmMasterData.map(function(b){return b.sku8D}).indexOf(c)}),b.rcmPIMSKU=b.rcmSKU.filter(function(c){return 0<=b.rcmMasterData.map(function(b){return b.sku8D}).indexOf(c)}))})},rcmPIMSKU:function(){var b=this;cartPromise(_api.search.price(),{eightcodes:this.rcmPIMSKU,channel:"WEB",basestore:"SS",pval:localStorage.customerGroup}).then(function(d){"200"==d.returncode&&
(b.rcmESData=d.data)})}},mounted:function(){queryGet("/services/sonystyle/score/search",function(b){if(0<b.length){var c=$(".bread_banner").attr("category"),e=$.cookie("score");b.forEach(function(b){if(b.category==c){b=b.score;var d=(new Date).getTime();if(void 0!==e){var f=e.split(","),k=f[0];console.log(d-k);if(2592E6<d-k)$.cookie("score",d+","+c+":"+b,{expires:30,path:"/"});else{d=!1;for(k=0;k<f.length;k++)if(0!=k){var m=f[k].split(":")[0],n=f[k].split(":")[1];m==c&&(f[k]=m+":"+(parseInt(n)+parseInt(b)),
d=!0)}d||f.push(c+":"+parseInt(b));$.cookie("score",f.join(","),{expires:30,path:"/"})}}else $.cookie("score",d+","+c+":"+b,{expires:30,path:"/"})}})}});var b=this;this.$nextTick(function(){function d(b){this.current=3;this.limit=4;this.wrap=$("#"+b);this.animz=this.wrap.find("ul");this.anili=this.animz.find("li");this.size=this.animz.find("li").size();this.prev=this.wrap.find(".tleft");this.next=this.wrap.find(".tright");this.lw=this.animz.find("li").outerWidth(!0)}$(".Prolist_pros").lunbo();$(".xxk_r ul li ").click(function(){$(".xxk_r ul li div").removeClass("onxxk");
$(this).find("div").addClass("onxxk");var b=$(this).data("id");$(".tab-ctrl-cont").find("."+b).show().siblings().hide();b=$(".pro_info").offset().top;$(document).scrollTop(b)});$(".specli a").bind("click",function(){var c=$(this).parent().attr("sku");void 0!==c&&$(this).attr("href",b.gotoPDP(c.split(",")[0]))});$(".colorli a").bind("click",function(){var c=$(this).parent().attr("sku");void 0!==c&&$(this).attr("href",b.gotoPDP(c))});d.prototype.gotoA=function(b){b>this.limit-1?this.animz.animate({marginLeft:-1*
(b-this.limit+1)*this.lw+"px"}):this.animz.animate({marginLeft:"0px"})};d.prototype.gotoLeft=function(){this.current--;3>this.current&&(this.current=3);this.gotoA(this.current)};d.prototype.gotoRight=function(){this.current++;this.current>this.size-1&&(this.current=this.size-1);this.gotoA(this.current)};d.prototype.init=function(){var b=this;b.size>b.limit&&(b.prev.css("display","block"),b.next.css("display","block"),b.prev.click(function(){b.gotoLeft()}),b.next.click(function(){b.gotoRight()}))};
d=new d("recomand");d.init();$(".rcm_con").find(".rc_ad a").bind("click",function(){var c=$(this).parents("li").attr("sku");b.__addToBasket(c,1)});$(".gallery-favorite").bind("click",function(){b.addToWishList()});$(".gallery-feedback").bind("click",function(){$(".survey-popup").bPopup();var b=s_gi("sonycnstyle");b.linkTrackVars="eVar11";b.eVar11="product:comments";b.tl(this,"o","product:comments:click");checkSubmit()})});$(".backtohead").bind("click",function(){$("html,body").animate({scrollTop:0},
300)});$(document).mouseup(function(d){var c=$(".coupons_conts"),e=$(".get_coupons");c.is(d.target)||0!==c.has(d.target).length||e.is(d.target)||0!==e.has(d.target).length||(b.showCoupon=!1)});$(".gotocompare").bind("click",function(){localStorage.compareArr=currentEightd})},methods:{clickCoupon:function(){this.showCoupon=!this.showCoupon},getCoupon:function(){var b=this;this._getCouponBy8D(this.sku).then(function(d){b.couponList=d.data;b.couponHeight=3<=b.couponList.length?"":"auto";b.couponIds=
b.couponList.map(function(b){return b.couponprefix})})},collectCoupon:function(b){var d=this;void 0!==localStorage.access_token&&""!==localStorage.access_token?this._collectCoupon(b).then(function(b){"00"!=b.resultMsg[0].code&&($(".errorbox .gmg p").eq(0).text(b.resultMsg[0].message),$(".errorbox").bPopup());d.getCoupon()}):$("#login").bPopup()},_getCouponBy8D:function(b){return(new Promise(function(d,c){cartPromise(_api.search.getCouponByProduct8D(),{eightcodes:[b]}).then(function(b){d(b)})})).catch(function(b){reject(b)})},
_collectCoupon:function(b){return new Promise(function(d,c){queryPromiseWithAuth(_api.HybrisAPI.collectCoupon(b),null,localStorage.access_token).then(function(b){d(b)})})},_checkCouponStatus:function(){var b=this;return new Promise(function(d,c){queryPromiseWithAuth(_api.HybrisAPI.getCouponStatus(),{couponId:b.couponIds},localStorage.access_token).then(function(b){d(b)})})},getCouponFinalStatus:function(b,d,c){if(c>(new Date).getTime())return"NOT_START";c=this.couponStatus.filter(function(c){return c.couponId==
b});var e="";0<c.length&&(e=c[0].allocated);return 1==e?"COLLECTED":d},showLogin:function(){$(".login_success").bPopup(function(){$(".denglu").trigger("click")})},remainTimeCountDonw:function(){var b=this;setInterval(function(){b.flashBuyRemainingTime=parseInt(b.flashBuyRemainingTime)-1E3;b.currentTimeSecond=parseInt(b.currentTimeSecond)+1E3;-1==b.flashflag?0>b.flashBuyRemainingTime&&(b.flashBuyRemainingTime=parseInt(b.flashStart)-parseInt(b.currentTimeSecond),b.flashflag=0,b.flashBuy=!0):0==b.flashflag?
0>b.flashBuyRemainingTime&&(b.flashBuyRemainingTime=parseInt(b.flashEnd)-parseInt(b.currentTimeSecond),b.flashflag=1):1==b.flashflag&&0>b.flashBuyRemainingTime&&(b.flashflag=2,b.flashBuy=!1)},1E3)},addToBasket:function(){null!=this.instalmentchecked1&&null!=this.instalmentchecked2?this.__instalmentAddToBasket(this.sku,this.instalmentData[this.instalmentchecked1].providerBanks[0].installmentEntries[this.instalmentchecked2].code,this.num).then(function(b){"99"===b.resultMsg[0].code&&($(".errorbox .gmg p").eq(0).text(b.resultMsg[0].message),
$(".errorbox").bPopup())}):this.__addToBasket(this.sku,this.num).then(function(b){_dtm_addToBasket=b})},flashBuyAddToBasket:function(){this.__flashBuyAddToBasket(this.sku).then(function(b){"99"===b.resultMsg[0].code&&($(".errorbox .gmg p").eq(0).text("\u8be5\u4ea7\u54c1\u7f3a\u8d27!"),$(".errorbox").bPopup())})},addToWishList:function(){var b=this;this.__addToWishList(this.sku).then(function(d){"00"==d.resultMsg[0].code&&(_dtm_addWishlistEntry=d,b.wishListFlag=!0)})},readWishList:function(){var b=
this;this.__readWishList().then(function(d){void 0!==d.resultData.wishList&&0<d.resultData.wishList.filter(function(c){return c.product8D===b.sku}).length&&(b.wishListFlag=!0)})},getPrice:function(){var b=this;return new Promise(function(d,c){cartPromise(_api.search.pricepromotion(),{eightcode:b.sku,channel:"WEB",basestore:"SS",pval:b.customerGroup}).then(function(c){if("200"==c.returncode){""!=b.customerGroup?(b.price=c.data.productprice.srp,b.regprice=c.data.productprice.regprice,b.memberPrice=
c.data.productprice.price,b.presalePrice=c.data.productprice.price,b.priceFlag="1"==b.memberPrice?"yqt":""):(b.presalePrice=c.data.productprice.srp,b.price=c.data.productprice.srp,b.regprice=c.data.productprice.regprice);600>c.data.productprice.price&&(b.instalmentPriceFlag=!0);b.memberPriceFlag=void 0!==c.data.productprice.memberpriceflag?c.data.productprice.memberpriceflag:"";var e=void 0!==c.data.promotelist?c.data.promotelist.filter(function(b){return"FOC"!=b.promotiontype&&"COUPON_PROMO"!=b.promotiontype}):
[],l=void 0!==c.data.cartpromotelist?c.data.cartpromotelist.filter(function(b){return"FOC"!=b.promotiontype&&"COUPON_PROMO"!=b.promotiontype}):[];b.promotionList=e.concat(l);b.focList=c.data.promotelist.filter(function(b){return"FOC"==b.promotiontype});b.cartFocList=c.data.cartpromotelist.filter(function(b){return"FOC"==b.promotiontype});b.salestatus=c.data.productprice.salestatus;b.storestatus=c.data.productprice.storestatus;b.pts=c.data.productprice.pts}d(c)}).catch(function(b){})})},getInstalment:function(){var b=
this;return new Promise(function(d,c){cartPromise(_api.search.getInstallmentList(),{channel:"WEB",productid:b.sku,pval:b.customerGroup}).then(function(b){d(b)}).catch(function(b){})})},mapBank:function(b){var d="";"CMB"==b?d="\u62db\u5546\u94f6\u884c":"ICBC"==b?d="\u5de5\u5546\u94f6\u884c":"ABC"==b?d="\u519c\u4e1a\u94f6\u884c":"BOC"==b?d="\u4e2d\u56fd\u94f6\u884c":"CCB"==b?d="\u5efa\u8bbe\u94f6\u884c":"HUABEI"==b&&(d="\u82b1\u5457\u5206\u671f");return d},clickInstalment:function(b,d){var c=this;"n"==
d?this.instalmentchecked2=this.instalmentchecked1=null:(this.getInstalment().then(function(b){"200"==b.returncode&&(c.instalmentData=b.data,c.instalmentShow=!0)}),this.instalmentchecked1=b,this.instalmentchecked2=d)},addNum:function(){this.num++;this.num>this.MAX_BUY_NUM&&(this.num=this.MAX_BUY_NUM)},reduce:function(){1>this.num||this.num--},numBlur:function(){var b=$(".num_p input").val();this.num=b>this.MAX_BUY_NUM?this.MAX_BUY_NUM:String(b).replace(/[^\d]/g,"")},showPromotion:function(){this.hideMorePromotion=
!1},hidePromotion:function(){this.hideMorePromotion=!0},transPromotionType:function(b){return"ORDER_THRESHOLD_PERCENTAGE_CART"==b||"ORDER_THRESHOLD_FIXED_DISCOUNT_CART"==b||"ORDER_THRESHOLD_PERCENTAGE_ALL"==b||"ORDER_THRESHOLD_FIXED_DISCOUNT_ALL"==b||"ORDER_THRESHOLD_PERCENTAGE_ANY"==b||"ORDER_THRESHOLD_FIXED_DISCOUNT_ANY"==b?"\u6ee1\u51cf":"PERFECT_PARTNER_PERCENTAGE_DISCOUNT_S"==b||"PERFECT_PARTNER_FIXED_DISCOUNT_S"==b||"PERFECT_PARTNER_FIXED_PRICE_S"==b||"PERFECT_PARTNER_PERCENTAGE_DISCOUNT_M"==
b||"PERFECT_PARTNER_FIXED_DISCOUNT_M"==b||"PERFECT_PARTNER_FIXED_PRICE_M"==b?"\u52a0\u4ef7\u8d2d":"SOFT_BUNDLE_PERCENTAGE_DISCOUNT"==b||"SOFT_BUNDLE_FIXED_PRICE"==b||"SOFT_BUNDLE_PROMO"==b?"\u5957\u88c5":"FOC_CART"==b?"\u6ee1\u8d60":"PRODUCT_PERCENTAGE_DISCOUNT"==b||"PRODUCT_FIXED_DISCOUNT"==b||"PRODUCT_FIXED_PRICE"==b?"\u4f18\u60e0":"\u4fc3\u9500"},getBuyMore:function(b){b=this.promotionList[b];var d=b.promotiontype;"\u52a0\u4ef7\u8d2d"==this.transPromotionType(d)&&(this.buyMoreFlag=d.substr(d.length-
1,1),this.buyMoreList=b.associatedproducts,this.firedmessage=b.firedmessage);"\u5957\u88c5"==this.transPromotionType(d)&&(this.buyMoreFlag="SS",this.buyMoreList=b.associatedproducts,this.firedmessage=b.firedmessage)},popupBuyMore:function(b){this.getBuyMore(b);$("#slim input").prop("checked",!1).show().css("visibility","visible");$(".buymore").bPopup()},buyMoreAddBasket:function(b){var d=$(b.currentTarget);b=d.attr("type");console.log(b);d=d.parent().parent().find("input:checked").map(function(){return $(this).attr("sku")}).toArray();
console.log(d);0<d.length&&("SS"==b&&d.push(this.sku),this.__multiAddToBasket(d,1))},checkBuyMore:function(b){b=$(b.currentTarget);if("S"==this.buyMoreFlag||"SS"==this.buyMoreFlag)b.prop("checked")?$("#slim input").not("input:checked").css("visibility","hidden"):$("#slim input").css("visibility","visible")},showRule:function(){$(".rule_main").show()},hideRule:function(){$(".rule_main").hide()},getLiveStatus:function(b){return new Promise(function(d,c){cartGetPromise(_api.live.getLiveInfoByName(b)).then(function(b){d(b)}).catch(function(b){})})},
inInstalment:function(b){$(b.currentTarget).addClass("active")},outInstalment:function(b){$(b.currentTarget).removeClass("active")},rtnSkinClass:function(b){return 9999<b?"wan":9999>=b&&999<b?"qian":"bai"},getRcmData:function(b,d){var c=this;$.get("https://recprd.csmc-cloud.com/omniapp/recommend/recommend/fetch?channel\x3dWEB\x26code\x3d"+this.sku,function(b){if(b.result&&"200"==b.code&&0<b.data.length){var d=b.data.filter(function(b){return"SameCategory"==b.relation}).map(function(b){return b.code}),
e=b.data.filter(function(b){return"Accessory"==b.relation}).map(function(b){return b.code}),g=b.data.filter(function(b){return"HotCategory"==b.relation}).map(function(b){return b.code}),k=b.data.filter(function(b){return"MapCategory"==b.relation}).map(function(b){return b.code});b=b.data.filter(function(b){return"MainBody"==b.relation}).map(function(b){return b.code});var m=[];if("default"==c.rcmFlag)c.rcmSKU.push.apply(c.rcmSKU,d.splice(0,2).map(function(b){return b.code})),c.rcmSKU.push.apply(c.rcmSKU,
k.splice(0,2).map(function(b){return b.code})),c.rcmSKU.push.apply(c.rcmSKU,e.splice(0,2).map(function(b){return b.code})),c.rcmSKU.push.apply(c.rcmSKU,g.splice(0,2).map(function(b){return b.code}));else{var n=c.rcmFlag.split("|");if(1<n.length&&""!=n[0])for(var q=0;q<n.length;q++){var h=n[q].split(":")[0],p=n[q].split(":")[1];if("\u540c\u54c1\u7c7b"==h)if(0<p)for(h=0;h<d.length;h++)h<p&&8>c.rcmSKU.length&&c.rcmSKU.push(d[h]);else d=[];else if("\u8de8\u54c1\u7c7b"==h)if(0<p)for(h=0;h<g.length;h++)h<
p&&8>c.rcmSKU.length&&c.rcmSKU.push(g[h]);else g=[];else if("\u5173\u8054\u54c1\u7c7b"==h)if(0<p)for(h=0;h<k.length;h++)h<p&&8>c.rcmSKU.length&&c.rcmSKU.push(k[h]);else k=[];else if("\u914d\u4ef6"==h)if(0<p)for(h=0;h<e.length;h++)h<p&&8>c.rcmSKU.length&&c.rcmSKU.push(e[h]);else e=[];else if("\u624b\u52a8"==h&&0<p&&void 0!==c.rcmManualSKU){var r=c.rcmManualSKU.split(",");for(h=0;h<r.length;h++)h<p&&8>c.rcmSKU.length&&(c.rcmSKU.push(r[h]),m.push(r[h]))}}}0<b.length&&(c.rcmSKU=b.map(function(b){return b.code}),
c.rcmSKU=m.concat(remSKUs))}})},filterRcmData:function(b,d){var c="";switch(d){case "price":c=0<this.rcmESData.filter(function(c){return c.eightcode==b}).length?this.rcmESData.filter(function(c){return c.eightcode==b})[0].price:"";break;case "salestatus":c=0<this.rcmESData.filter(function(c){return c.eightcode==b}).length?this.rcmESData.filter(function(c){return c.eightcode==b})[0].salestatus:"";break;case "storestatus":c=0<this.rcmESData.filter(function(c){return c.eightcode==b}).length?this.rcmESData.filter(function(c){return c.eightcode==
b})[0].storestatus:"";break;case "pdpurl":c=0<this.rcmMasterData.filter(function(c){return c.sku8D==b}).length?this.rcmMasterData.filter(function(c){return c.sku8D==b})[0].pdpurl:"#";break;case "enName":c=0<this.rcmMasterData.filter(function(c){return c.sku8D==b}).length?this.rcmMasterData.filter(function(c){return c.sku8D==b})[0].enName:"";break;case "cnName":c=0<this.rcmMasterData.filter(function(c){return c.sku8D==b}).length?this.rcmMasterData.filter(function(c){return c.sku8D==b})[0].cnName:"";
break;case "imagePath":c=0<this.rcmMasterData.filter(function(c){return c.sku8D==b}).length?this.rcmMasterData.filter(function(c){return c.sku8D==b})[0].imagePath:""}return c},switchRcm:function(b){var d=this;if(!this.rcmScroll){this.rcmScroll=!0;console.log(this.rcmScroll);var c=this.rcmData.length,e=$("#ctuijian").css("marginLeft").replace("px","");"L"==b?-300*(c-4)!=parseInt(e)&&$("#ctuijian").animate({marginLeft:parseInt(e)+-300+"px"},400):0!=e&&$("#ctuijian").animate({marginLeft:parseInt(e)-
-300+"px"},400);setTimeout(function(){d.rcmScroll=!1},400)}}}}),new Vue({el:"#comments",data:{overallReviewStatus:{},originReviews:[],reviews:[],sku:[],high:0,middle:0,low:0,onlyshow:!1,thisSku:$(".bread_banner").attr("sku"),rating:"",pageSize:"10",withAttachment:"0",totalNoOfPages:0,totalNoOfRecords:0,totalData:0},created:function(){var b=this,d=this;$(".specli li").each(function(){d.sku=new Set([].concat($jscomp.arrayFromIterable(d.sku),$jscomp.arrayFromIterable($(this).attr("sku").split(","))))});
this.getReviews("0",this.pageSize,"","").then(function(c){"00"==c.resultMsg[0].code&&(b.overallReviewStatus=c.resultData.overallReviewStatus,b.totalData=c.resultData.overallReviewStatus.totalCount,b.reviews=b.originReviews=c.resultData.reviews,b.high=parseInt(c.resultData.overallReviewStatus.rating4)+parseInt(c.resultData.overallReviewStatus.rating5),b.middle=parseInt(c.resultData.overallReviewStatus.rating2)+parseInt(c.resultData.overallReviewStatus.rating3),b.low=parseInt(c.resultData.overallReviewStatus.rating1),
void 0!==c.resultData.reviews&&0<c.resultData.reviews.length&&$("li.tab-comments").show());b.totalNoOfPages=c.resultData.totalNoOfPages;b.totalNoOfRecords=c.resultData.totalNoOfRecords;b.setPagination()})},watch:{onlyshow:function(){this.doFilter()},withAttachment:function(){this.doFilter()},rating:function(){this.doFilter()}},methods:{getReviews:function(b,d,c,e){var f=this;return new Promise(function(l,g){cartPromise(_api.HybrisAPI.getProductReviews(),{product8D:f.onlyshow?f.thisSku:[].concat($jscomp.arrayFromIterable(f.sku)),
pageNumber:b,pageSize:d,rating:c,withAttachment:e}).then(function(b){l(b);$(".pic_list_m").hide()}).catch(function(b){})})},setPagination:function(){var b=this;$(".pagination-box").empty();$(".pagination-box").Page({totalPages:b.totalNoOfPages,liNums:5,activeClass:"activP",callBack:function(d){b.getReviews((d-1).toString(),b.pageSize,b.rating,b.withAttachment).then(function(c){"00"==c.resultMsg[0].code&&(b.reviews=b.originReviews=c.resultData.reviews,c=$(".tab-ctrl-cont").offset().top,$("html,body").animate({scrollTop:c},
"slow"))})}})},changeProduct:function(){this.onlyshow=this.onlyshow?!1:!0},changeAttachment:function(){this.withAttachment="1"==this.withAttachment?"0":"1"},changeFilter:function(b){this.rating=b},doFilter:function(){var b=this;this.getReviews("0",this.pageSize,this.rating,this.withAttachment).then(function(d){"00"==d.resultMsg[0].code&&(b.overallReviewStatus=d.resultData.overallReviewStatus,b.totalData="GOOD"==b.rating?parseInt(d.resultData.overallReviewStatus.rating4)+parseInt(d.resultData.overallReviewStatus.rating5):
"MODERATE"==b.rating?parseInt(d.resultData.overallReviewStatus.rating2)+parseInt(d.resultData.overallReviewStatus.rating3):"POOR"==b.rating?parseInt(d.resultData.overallReviewStatus.rating1):d.resultData.overallReviewStatus.totalCount,b.reviews=b.originReviews=d.resultData.reviews,b.high=parseInt(d.resultData.overallReviewStatus.rating4)+parseInt(d.resultData.overallReviewStatus.rating5),b.middle=parseInt(d.resultData.overallReviewStatus.rating2)+parseInt(d.resultData.overallReviewStatus.rating3),
b.low=parseInt(d.resultData.overallReviewStatus.rating1),b.totalNoOfPages=d.resultData.totalNoOfPages,b.totalNoOfRecords=d.resultData.totalNoOfRecords,b.setPagination())})},showBigImage:function(b,d,c,e){e=$(e.currentTarget);e.parent().find("a").removeClass("pic_item_current");e.addClass("pic_item_current");e=e.parent().parent().find(".pic_list_m");var f=e.find(".p_prev"),l=e.find(".p_next");e.find("img").attr("src",c.image);f.show();l.show();0==b?f.hide():b==d-1&&l.hide();e.attr("cur",b);e.show()},
showNextBigImage:function(b,d){var c=$(b.currentTarget),e=$(b.currentTarget).parent().parent().attr("cur");if(void 0!==e&&e<d-1){var f=c.parent().parent().parent().find(".pic_item").eq(parseInt(e)+1),l=f.find("span").attr("image");f.parent().find("a").removeClass("pic_item_current");f.addClass("pic_item_current");c.parent().find("img").attr("src",l)}$(b.currentTarget).parent().parent().attr("cur",parseInt(e)+1==d?e:parseInt(e)+1);e+1==d-1&&c.hide();c.parent().find(".p_prev").show()},showPrevBigImage:function(b,
d){d=$(b.currentTarget);var c=$(b.currentTarget).parent().parent().attr("cur");if(void 0!==c&&0!=c){var e=d.parent().parent().parent().find(".pic_item").eq(parseInt(c)-1),f=e.find("span").attr("image");e.parent().find("a").removeClass("pic_item_current");e.addClass("pic_item_current");d.parent().find("img").attr("src",f)}$(b.currentTarget).parent().parent().attr("cur",0>parseInt(c)-1?0:parseInt(c)-1);0==c-1&&d.hide();d.parent().find(".p_next").show()},hideBigImage:function(b){$(b.currentTarget).parent().parent().hide()}}}))});
