var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(b.call(c,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");var _dtm_login_getMemberInfo;
$(function(){-1==window.location.href.indexOf("onlyShowFeature\x3dtrue")&&new Vue({el:"#login",data:{login_data:{loginID:$.cookie("memberID"),password:"",channel:"WEB"},register_data:{registrationChannel:"WEB",registerType:"QUICK",emailSubscribe:"1",mobile:"",email:"",pwd:"",cpwd:"",otpCode:""},processing:!1,reg:{phone:/^1[0123456789][0-9]{9}$/,email:/^[a-zA-Z0-9_.-]+@[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*\.[a-zA-Z0-9]{2,6}$/,pwd:/^(?=.*[a-zA-Z])(?=.*\d)[a-zA-Z\d!@#\$%&\-_\.\]\*\$]{8,40}$/},otp_data:{otpType:"USER_REGISTRATION",
mobile:"",captchaCode:""},agree_policy:"",mobileErr:{show:"none",msg:""},pwdErr:{show:"none",msg:""},cpwdErr:{show:"none",msg:""},huoquErr:{show:"none",msg:""},send_otpErr:{show:"none",msg:""},emailErr:{show:"none",msg:""},otpErr:{show:"none",msg:""},agrErr:{show:"none",msg:"\u8bf7\u540c\u610f\u7528\u6237\u534f\u8bae"},showLoginSlider:void 0!==localStorage.showLoginSlider?localStorage.showLoginSlider:!1,showRegSlider:void 0!==localStorage.showRegSlider?localStorage.showRegSlider:!1,loginError:"",
check_mobile:!1,check_email:!1,check_pwd:!1,check_cpwd:!1,check_agr:!1,check_otp:!1},created:function(){localStorage.getItem("login_nc_token_header")&&localStorage.removeItem("login_nc_token_header");localStorage.getItem("login_session_id_header")&&localStorage.removeItem("login_session_id_header");localStorage.getItem("login_sig_header")&&localStorage.removeItem("login_sig_header");localStorage.getItem("register_nc_token_header")&&localStorage.removeItem("register_nc_token_header");localStorage.getItem("register_session_id_header")&&
localStorage.removeItem("register_session_id_header");localStorage.getItem("register_sig_header")&&localStorage.removeItem("register_sig_header");var a=this;void 0!==localStorage.access_token&&""!=localStorage.access_token&&this.__getMemberInfo().then(function(a){_dtm_login_getMemberInfo=a;0<$("#myLoginStatus").length&&($("#myLoginWrap").hide(),$("body").hasClass("mobile")||($("#myLoginStatus").show(),$("#myLoginStatus").find("p").eq(0).addClass(a.resultData.customerGroup).text(a.resultData.userAlias),
localStorage.setItem("customerGroup",a.resultData.customerGroup),localStorage.setItem("customerID",a.resultData.customerID)),$(".new-menu .status-bar .user img").attr("src",a.resultData.avatarPath),$(".new-menu .status-bar .user .login-info").html('\x3cspan class\x3d"hello"\x3e\u60a8\u597d\uff01\x3c/span\x3e\x3cspan class\x3d"name"\x3e'+a.resultData.userAlias+"\x3c/span\x3e"))});$("#myLoginStatus .loginLink").bind("click",function(){a.logout()})},mounted:function(){var a=this;this.$nextTick(function(){$(".zhuce").bind("click",
function(){$(".login_zones").hide();$(".register_zones").show()});$(".denglu").bind("click",function(){$(".login_zones").show();$(".register_zones").hide()});$(".btn_t").each(function(a,b){$(this).click(function(){$(this).hasClass("zhuce_active")||($(this).siblings().removeClass("zhuce_active"),$(this).addClass("zhuce_active"),$(".zhuce_con").hide(),$(".zhuce_con").eq(a).show())})});$("#myLoginWrap .loginLink").bind("click",function(){$(this).hasClass("logined")?$(".login_success").bPopup(function(){$(".denglu").trigger("click")}):
$(".login_success").bPopup(function(){$(".zhuce").trigger("click")})});$(".new-menu .new-login").bind("click",function(){$(".login_success").bPopup(function(){$(".denglu").trigger("click")})});$(".new-menu .new-register").bind("click",function(){$(".login_success").bPopup(function(){$(".zhuce").trigger("click")})});var b=["FFFF0N00000000000A7C",(new Date).getTime(),Math.random()].join(":");(new noCaptcha({renderTo:"#aliverifyHeader1",appkey:"FFFF0N00000000000A7C",scene:"nc_message",token:b,customWidth:316,
trans:{key1:"code0"},elementID:["usernameID"],is_Opt:0,language:"cn",isEnabled:!0,timeout:3E3,times:5,apimap:{},callback:function(a){localStorage.setItem("login_nc_token_header",b);localStorage.setItem("login_session_id_header",a.csessionid);localStorage.setItem("login_sig_header",a.sig)}})).upLang("cn",{_startTEXT1:"\u8bf7\u5148\u6309\u4f4f\u6ed1\u5757\u6ed1\u52a8\u5230\u6700\u53f3\u8fb9\uff0c\u518d\u767b\u9646",_yesTEXT:"\u9a8c\u8bc1\u901a\u8fc7",_error300:'\u54ce\u5440\uff0c\u51fa\u9519\u4e86\uff0c\u70b9\u51fb\x3ca href\x3d"javascript:__nc.reset()"\x3e\u5237\u65b0\x3c/a\x3e\u518d\u6765\u4e00\u6b21',
_errorNetwork:'\u7f51\u7edc\u4e0d\u7ed9\u529b\uff0c\u8bf7\x3ca href\x3d"javascript:__nc.reset()"\x3e\u70b9\u51fb\u5237\u65b0\x3c/a\x3e'});var c=["FFFF0N00000000000A7C",(new Date).getTime(),Math.random()].join(":");(new noCaptcha({renderTo:"#aliverifyHeader2",appkey:"FFFF0N00000000000A7C",scene:"nc_message",token:c,customWidth:316,trans:{key1:"code0"},elementID:["usernameID"],is_Opt:0,language:"cn",isEnabled:!0,timeout:3E3,times:5,apimap:{},callback:function(b){localStorage.setItem("register_nc_token_header",
c);localStorage.setItem("register_session_id_header",b.csessionid);localStorage.setItem("register_sig_header",b.sig);"\u8bf7\u62d6\u52a8\u4e0a\u65b9\u6ed1\u5757\u518d\u83b7\u53d6\u9a8c\u8bc1\u7801"==a.otpErr.msg&&(a.otpErr.show="none")}})).upLang("cn",{_startTEXT2:"\u8bf7\u5148\u6309\u4f4f\u6ed1\u5757\u6ed1\u52a8\u5230\u6700\u53f3\u8fb9\uff0c\u518d\u83b7\u53d6\u77ed\u4fe1\u9a8c\u8bc1\u7801",_yesTEXT:"\u9a8c\u8bc1\u901a\u8fc7",_error300:'\u54ce\u5440\uff0c\u51fa\u9519\u4e86\uff0c\u70b9\u51fb\x3ca href\x3d"javascript:__nc.reset()"\x3e\u5237\u65b0\x3c/a\x3e\u518d\u6765\u4e00\u6b21',
_errorNetwork:'\u7f51\u7edc\u4e0d\u7ed9\u529b\uff0c\u8bf7\x3ca href\x3d"javascript:__nc.reset()"\x3e\u70b9\u51fb\u5237\u65b0\x3c/a\x3e'})})},methods:{login:function(){var a=this;this.processing||(this.processing=!0,this.showLoginSlider&&(this.login_data.token=localStorage.getItem("login_nc_token_header"),this.login_data.sessionId=localStorage.getItem("login_session_id_header"),this.login_data.sig=localStorage.getItem("login_sig_header"),this.login_data.scene="nc_message",this.login_data.appKey="FFFF0N00000000000A7C"),
this._login(this.login_data).then(function(b){a.processing=!1;"00"==b.resultMsg[0].code?(window._dacq&&_dacq.login&&_dacq.login(),$(".login_info input[type\x3dcheckbox]").prop("checked")&&($.cookie("memberID","",{path:"/",expires:-1}),$.cookie("memberID",a.login_data.loginID,{path:"/",expires:7})),localStorage.setItem("showLoginSlider",!1),dochat&&0>document.URL.indexOf("chat\x3dtrue")?window.location.href=document.URL+"?chat\x3dtrue":window.location.reload()):("99"==b.resultMsg[0].code&&void 0!==
b.resultData&&(localStorage.setItem("showLoginSlider",!0),a.showLoginSlider=!0,localStorage.getItem("login_nc_token_header")&&localStorage.removeItem("login_nc_token_header"),localStorage.getItem("login_session_id_header")&&localStorage.removeItem("login_session_id_header"),localStorage.getItem("login_sig_header")&&localStorage.removeItem("login_sig_header")),a.loginError=b.resultMsg[0].message)}).catch(function(b){console.log(b);a.loginError=b.responseJSON.resultMsg[0].message;a.processing=!1}))},
onKeyDown:function(){this.login()},logout:function(){this._logout().then(function(a){"00"==a.resultMsg[0].code&&(localStorage.setItem("access_token",""),localStorage.setItem("customerGroup",""),localStorage.setItem("customerID",""),window.location.reload())})},checkMobile:function(){var a=this;""==this.register_data.mobile&&(this.mobileErr.show="block",this.mobileErr.msg="\u624b\u673a\u53f7\u4e0d\u80fd\u4e3a\u7a7a",this.check_mobile=!1);this.reg.phone.test(this.register_data.mobile)?axios({method:"POST",
url:_api.HybrisAPI.isMobileAvailable(),data:{mobile:this.register_data.mobile}}).then(function(b){"00"!=b.data.resultMsg[0].code?(a.mobileErr.show="block",a.mobileErr.msg=b.data.resultMsg[0].message,a.check_mobile=!1):(a.mobileErr.show="none",a.mobileErr.msg="",a.check_mobile=!0)}).catch(function(a){}):(this.mobileErr.show="block",this.mobileErr.msg="\u8bf7\u8f93\u5165\u6b63\u786e\u7684\u624b\u673a\u53f7\u7801",this.check_mobile=!1)},checkEmail:function(){var a=this;this.reg.email.test(this.register_data.email)?
axios({method:"POST",url:_api.HybrisAPI.isEmailIdExists(),data:{emailId:this.register_data.email}}).then(function(b){"00"!=b.data.resultMsg[0].code?(a.emailErr.show="block",a.emailErr.msg=b.data.resultMsg[0].message,a.check_email=!1):(a.emailErr.show="none",a.emailErr.msg="",a.check_email=!0)}).catch(function(a){alert(a)}):(this.emailErr.show="block",this.emailErr.msg="\u8bf7\u8f93\u5165\u6b63\u786e\u7684\u90ae\u7bb1\u53f7",this.check_email=!1)},checkPwd:function(){this.reg.pwd.test(this.register_data.pwd)?
(this.pwdErr.show="none",this.pwdErr.msg="",this.check_pwd=!0):(this.pwdErr.show="block",this.pwdErr.msg="\u8bf7\u8f93\u5165\u75318-40\u4e2a\u5b57\u7b26\u7ec4\u6210\uff0c\u987b\u542b\u5b57\u6bcd\u548c\u6570\u5b57\u7684\u5bc6\u7801",this.check_pwd=!1)},checkCpwd:function(){this.register_data.pwd==this.register_data.cpwd&&""!==this.register_data.pwd?(this.cpwdErr.show="none",this.check_cpwd=!0):(this.cpwdErr.show="block",this.cpwdErr.msg="\u4e24\u6b21\u8f93\u5165\u7684\u5bc6\u7801\u4e0d\u4e00\u81f4",
this.check_cpwd=!1)},checkAgr:function(){"1"!=this.agree_policy?(this.agrErr.show="block",this.check_agr=!1):(this.agrErr.show="none",this.check_agr=!0)},checkOtp:function(){""==this.register_data.otpCode?(this.otpErr.show="block",this.otpErr.msg="\u8bf7\u8f93\u5165\u9a8c\u8bc1\u7801",this.check_otp=!1):(this.otpErr.show="none",this.check_otp=!0)},empty_mobile:function(){this.register_data.mobile=""},empty_email:function(){this.register_data.email=""},register:function(){var a=this;this.processing||
(this.processing=!0,this.checkMobile(),this.checkCpwd(),this.checkPwd(),this.checkAgr(),this.checkOtp(),this.cpwdErr.msg="\u518d\u6b21\u8f93\u5165\u5bc6\u7801",this.check_mobile&&this.check_pwd&&this.check_cpwd&&this.check_agr&&this.check_otp&&axios({method:"POST",url:_api.HybrisAPI.register(),data:this.register_data}).then(function(b){a.processing=!1;"\u8bf7\u8f93\u5165\u6b63\u786e\u7684\u77ed\u4fe1\u9a8c\u8bc1\u7801"==b.data.resultMsg[0].message?(a.send_otpErr.show="block",a.send_otpErr.msg="\u8bf7\u8f93\u5165\u6b63\u786e\u7684\u77ed\u4fe1\u9a8c\u8bc1\u7801"):
"00"==b.data.resultMsg[0].code&&(a.send_otpErr.show="none",localStorage.setItem("access_token",b.data.resultData.access_token),window.location.reload())}).catch(function(b){a.processing=!1}))},send_otp:function(){if(this.check_mobile){var a=function(){$(".span_countdown span").html(b);setTimeout(function(){b--;0>b?($(".huoqu1").show(),$(".huoqu2").hide(),b=120):a()},1E3)},b=120;if(""==this.register_data.mobile)this.mobileErr.show="block",this.mobileErr.msg="\u624b\u673a\u53f7\u7801\u4e0d\u80fd\u4e3a\u7a7a";
else if(void 0==localStorage.register_session_id_header||void 0==localStorage.register_sig_header||void 0==localStorage.register_nc_token_header)this.otpErr.show="block",this.otpErr.msg="\u8bf7\u62d6\u52a8\u4e0a\u65b9\u6ed1\u5757\u518d\u83b7\u53d6\u9a8c\u8bc1\u7801";else{$(".huoqu1").hide();$(".huoqu2").show();a();this.otpErr.show="none";var c={otpType:"USER_REGISTRATION",mobile:this.register_data.mobile,sessionId:localStorage.register_session_id_header,sig:localStorage.register_sig_header,token:localStorage.register_nc_token_header,
appKey:"FFFF0N00000000000A7C",scene:"nc_message"}}this.otp_data.mobile=this.register_data.mobile;axios({method:"POST",url:_api.HybrisAPI.sendOTP(),data:c}).then(function(a){}).catch(function(a){})}},targetTaobaoPagePath:function(){localStorage.setItem("thirdParty","TAOBAO");window.location.href="https://oauth.taobao.com/authorize?response_type\x3dcode\x26client_id\x3d27628610\x26redirect_uri\x3d"+window.location.href+"\x26state\x3d200\x26view\x3dweb"},targetWechatPagePath:function(){$(".wechat.later")||
$(".weibo.later")||$(".zhifubao.later")?$(".other_tip").show():$(".other_tip").hide()}}})});
