var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){a!=Array.prototype&&a!=Object.prototype&&(a[b]=d.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();var b=a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.polyfill=function(a,b,d,e){if(b){d=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var c=a[e];c in d||(d[c]={});d=d[c]}a=a[a.length-1];e=d[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:b})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function d(a){return a instanceof c?a:new c(function(f,b){f(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(a);return this};b.prototype.asyncExecuteBatch_=function(){var a=this;this.asyncExecuteFunction(function(){a.executeBatch_()})};var e=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){e(a,
0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];delete a[b];try{c()}catch(k){this.asyncThrow_(k)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var c=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var f=this.createResolveAndReject_();try{a(f.resolve,f.reject)}catch(h){f.reject(h)}};c.prototype.createResolveAndReject_=
function(){function a(a){return function(f){c||(c=!0,a.call(b,f))}}var b=this,c=!1;return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};c.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof c)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};c.prototype.resolveToNonPromiseObj_=function(a){var b=
void 0;try{b=a.then}catch(h){this.reject_(h);return}"function"==typeof b?this.settleSameAsThenable_(b,a):this.fulfill_(a)};c.prototype.reject_=function(a){this.settle_(2,a)};c.prototype.fulfill_=function(a){this.settle_(1,a)};c.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b|"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};c.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
this.onSettledCallbacks_,b=0;b<a.length;++b)a[b].call(),a[b]=null;this.onSettledCallbacks_=null}};var g=new b;c.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};c.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(k){c.reject(k)}};c.prototype.then=function(a,b){function d(a,b){return"function"==typeof a?function(b){try{e(a(b))}catch(l){f(l)}}:b}var e,f,g=new c(function(a,
b){e=a;f=b});this.callWhenSettled_(d(a,e),d(b,f));return g};c.prototype.catch=function(a){return this.then(void 0,a)};c.prototype.callWhenSettled_=function(a,b){function c(){switch(d.state_){case 1:a(d.result_);break;case 2:b(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?g.asyncExecute(c):this.onSettledCallbacks_.push(function(){g.asyncExecute(c)})};c.resolve=d;c.reject=function(a){return new c(function(b,c){c(a)})};c.race=function(a){return new c(function(b,
c){for(var e=$jscomp.makeIterator(a),f=e.next();!f.done;f=e.next())d(f.value).callWhenSettled_(b,c)})};c.all=function(a){var b=$jscomp.makeIterator(a),e=b.next();return e.done?d([]):new c(function(a,c){function f(b){return function(c){g[b]=c;h--;0==h&&a(g)}}var g=[],h=0;do g.push(void 0),h++,d(e.value).callWhenSettled_(f(g.length-1),c),e=b.next();while(!e.done)})};return c},"es6","es3");window._api={};var apiDomain="",apiShopOrder="",apiShopCar="",apiSearch="",apiLive="https://weixin.csmc-cloud.com";
_api.productInformation={getInformation:function(){return apiDomain+"/pim/out?method\x3dfindMasterData"},getInformationList:function(){return apiDomain+"/pim/out?method\x3dfindMasterDataList"},getSpec:function(){return apiDomain+"/pim/out?method\x3dfindSpecCompare"},getAccy:function(){return apiDomain+"/pim/out?method\x3dfindProductAccessory"},getMasterData:function(){return apiShopOrder+"/eSolverOmniChannel/masterData/cityMaster.do"},getMainSpec:function(){return apiDomain+"/pim/out?method\x3dfindMainSpec"},
getDetailSpec:function(){return apiDomain+"/pim/out?method\x3dfindDetailSpec"},getDetailSpecCompare:function(){return apiDomain+"/pim/out?method\x3dfindDetailSpecCompare"},getCompareList:function(){return apiDomain+"/pim/out?method\x3dfindCompareList"}};
_api.bbsAPI={getInvication:function(a){return apiDomain+"/mysony/bbsapp/index.php?app\x3dgroup\x26ac\x3dapi\x26api\x3dbbs\x26ts\x3duse_models_topic\x26en_name\x3d"+a},saveInvicationList:function(){return apiShopCar+"/pim/series/invication?method\x3dupdate"},getInvicationFromAem:function(){return apiShopCar+"/pim/series/invication?method\x3dfindOne"}};
_api.caschAPI={getModelPath:function(a){return apiDomain+"/casch/homePage?method\x3dfindProModel\x26keyword\x3d"+a},getModelURL:function(a){return apiDomain+"/casch/homePage?method\x3dfindModelUrl\x26path\x3d"+a},getCaSCHModelPath:function(a){return apiDomain+"/services/sonystyle/casch?sku\x3d"+a}};
_api.HybrisAPI={login:function(){return apiShopCar+"/eSolverOmniChannel/account/login.do"},logout:function(a){return apiShopCar+"/eSolverOmniChannel/account/logout.do?access_token\x3d"+a},readCart:function(a){return apiShopCar+"/eSolverOmniChannel/order/readCart.do?access_token\x3d"+a+"\x26channel\x3dWEB"},addToBasket:function(a){return apiShopCar+"/eSolverOmniChannel/order/addToBasket.do?access_token\x3d"+a+"\x26channel\x3dWEB"},changeCart:function(a){return apiShopCar+"/eSolverOmniChannel/order/changeCart.do?access_token\x3d"+
a+"\x26channel\x3dWEB"},checkout:function(a){return apiShopCar+"/eSolverOmniChannel/order/checkout.do?access_token\x3d"+a+"\x26channel\x3dWEB"},miniCartDisplay:function(a){return apiShopCar+"/eSolverOmniChannel/order/miniCartDisplay.do?access_token\x3d"+a+"\x26channel\x3dWEB"},displayCaptcha:function(){return apiShopCar+"/eSolverOmniChannel/account/displayCaptcha.do"},register:function(){return apiShopCar+"/eSolverOmniChannel/account/register.do"},sendOTP:function(){return apiShopCar+"/eSolverOmniChannel/account/sendOTP.do"},
isMobileAvailable:function(){return apiShopCar+"/eSolverOmniChannel/account/isMobileAvailable.do"},isEmailIdExists:function(){return apiShopCar+"/eSolverOmniChannel/account/isEmailIdExists.do"},masterData:function(a){return apiShopCar+"/eSolverOmniChannel/masterData/cityMaster.do?access_token\x3d"+a},addShipToAddress:function(a){return apiShopCar+"/eSolverOmniChannel/address/addShipToAddress.do?access_token\x3d"+a+"\x26channel\x3dWEB"},getShipToList:function(a){return apiShopCar+"/eSolverOmniChannel/address/getShipToList.do?access_token\x3d"+
a+"\x26channel\x3dWEB"},editShipToAddress:function(a){return apiShopCar+"/eSolverOmniChannel/address/editShipToAddress.do?access_token\x3d"+a+"\x26channel\x3dWEB"},deleteShipToAddress:function(a){return apiShopCar+"/eSolverOmniChannel/address/deleteShipToAddress.do?access_token\x3d"+a+"\x26channel\x3dWEB"},setDefaultShipTo:function(a){return apiShopCar+"/eSolverOmniChannel/address/setDefaultShipTo.do?access_token\x3d"+a+"\x26channel\x3dWEB"},getShipToAddress:function(a){return apiShopCar+"/eSolverOmniChannel/address/getShipToAddress.do?access_token\x3d"+
a+"\x26channel\x3dWEB"},getDefaultShipTo:function(a){return apiShopCar+"/eSolverOmniChannel/address/getDefaultShipTo.do?access_token\x3d"+a+"\x26channel\x3dWEB"},createOrder:function(a){return apiShopCar+"/eSolverOmniChannel/order/createOrder.do?access_token\x3d"+a+"\x26channel\x3dWEB"},getOrder:function(a){return apiShopCar+"/eSolverOmniChannel/order/getOrder.do?access_token\x3d"+a+"\x26channel\x3dWEB"},getCartPromotions:function(a){return apiShopCar+"/eSolverOmniChannel/coupon/getCartPromotions.do?access_token\x3d"+
a+"\x26channel\x3dWEB"},getCaptcha:function(a){return apiShopCar+"/eSolverOmniChannel/account/displayCaptcha.do?"+a},getMemberInfo:function(a){return apiShopCar+"/eSolverOmniChannel/account/getMemberInfo.do?access_token\x3d"+a+"\x26channel\x3dWEB"},addWishlistEntry:function(a){return apiShopCar+"/eSolverOmniChannel/wishlist/addWishlistEntry.do?access_token\x3d"+a+"\x26channel\x3dWEB"},moveToWishlist:function(a){return apiShopCar+"/eSolverOmniChannel/wishlist/moveToWishlist.do?access_token\x3d"+a+
"\x26channel\x3dWEB"},readWishlist:function(a){return apiShopCar+"/eSolverOmniChannel/wishlist/readWishlist.do?access_token\x3d"+a+"\x26channel\x3dWEB"},getProductReviews:function(){return apiShopCar+"/eSolverOmniChannel/review/getProductReviews.do?channel\x3dWEB"},getProductCoupon:function(a){return apiShopCar+"/eSolverOmniChannel/coupon/getItemCouponList.do?access_token\x3d"+a+"\x26channel\x3dWEB"},applyCoupon:function(a){return apiShopCar+"/eSolverOmniChannel/coupon/applyCoupon.do?access_token\x3d"+
a+"\x26channel\x3dWEB"},releaseCoupon:function(a){return apiShopCar+"/eSolverOmniChannel/coupon/releaseCoupon.do?access_token\x3d"+a+"\x26channel\x3dWEB"},getOrderList:function(a){return apiShopCar+"/eSolverOmniChannel/account/getOrdersHistory.do?access_token\x3d"+a+"\x26channel\x3dWEB"},getCountDownTime:function(){return apiShopCar+"/eSolverOmniChannel/coupon/getCountDownTime.do"},getAlipayOnlinePayment:function(a){return apiShopCar+"/eSolverOmniChannel/order/alipayOnlinePayment.do?access_token\x3d"+
a+"\x26channel\x3dWEB"},flashBuyAddtoBasket:function(a){return apiShopCar+"/eSolverOmniChannel/order/addFlashBuyToBasket.do?access_token\x3d"+a+"\x26channel\x3dWEB"},getRegProductList:function(a){return apiShopCar+"/eSolverOmniChannel/account/getProductsHistory.do?access_token\x3d"+a+"\x26channel\x3dWEB"},validateAccessToken:function(a){return apiShopCar+"/eSolverOmniChannel/account/validateAccessToken.do?access_token\x3d"+a},getPersonalDetail:function(a){return apiShopCar+"/eSolverOmniChannel/account/getPersonalDetails.do?access_token\x3d"+
a},getCouponStatus:function(){return apiShopCar+"/eSolverOmniChannel/coupon/couponStatus.do"},collectCoupon:function(a){return apiShopCar+"/eSolverOmniChannel/coupon/collectCoupon.do?couponPrefix\x3d"+a},getInstallmentPayInfo:function(a){return apiShopCar+"/eSolverOmniChannel/order/installmentPayInfo.do?access_token\x3d"+a},getUnionPayOnlinePayment:function(a){return apiShopCar+"/eSolverOmniChannel/order/unionPayOnlinePayment.do?access_token\x3d"+a+"\x26channel\x3dWEB"},addToInstallmentBasket:function(a,
b){return apiShopCar+"/eSolverOmniChannel/order/addToInstallmentBasket.do?access_token\x3d"+a+"\x26channel\x3dWEB\x26installmententrycode\x3d"+b},getUnionPayInstallPayment:function(a){return apiShopCar+"/eSolverOmniChannel/order/unionPayInstallmentPayment.do?access_token\x3d"+a+"\x26channel\x3dWEB"}};
_api.search={getsearchresult:function(){return apiSearch+"/b2csearch/esapi/product/getsearchresult"},autosuggestion:function(){return apiSearch+"/b2csearch/esapi/keyword/autosuggestion/"},similar:function(){return apiSearch+"/b2csearch/esapi/keyword/similar/"},getAbout:function(){return apiSearch+"https://recprd.csmc-cloud.com/omniapp/recommend/recommend/fetch"},price:function(){return apiSearch+"/b2csearch/esapi/product/price"},pricepromotion:function(){return apiSearch+"/b2csearch/esapi/product/pricepromotion"},
multipricepromotion:function(){return apiSearch+"/b2csearch/esapi/product/multipricepromotion"},getArea:function(a){return apiSearch+"/b2csearch/esapi/area/areas?parentcode\x3d"+a},getCouponByProduct8D:function(){return apiSearch+"/b2csearch/esapi/coupon/getcouponbyproduct8D"},getIsInstallmentProduct:function(){return apiSearch+"/b2csearch/esapi/installment/getRecommendInstallmentList"},getInstallmentList:function(){return apiSearch+"/b2csearch/esapi/installment/getInstallmentList"},getRecommendInstallmentList:function(){return apiSearch+
"/b2csearch/esapi/installment/getRecommendInstallmentList"}};_api.survey={commitSurvey:function(a,b,d,e,c,g){return"/omniapp/storesurvey/feedback/commit?comments\x3d"+a+"\x26commitUrl\x3d"+b+"\x26site\x3d"+d+"\x26customerID\x3d"+e+"\x26type\x3d"+c+"\x26title\x3d"+g}};_api.live={getLiveInfoByName:function(a){return apiLive+"/livehappyprd/back/getLiveInfoByName?modelName\x3d"+a}};
function query(a,b,d,e){$.ajax({url:a,contentType:"application/json; charset\x3dUTF-8",type:"post",async:"undefined"===typeof e?!1:!0,data:JSON.stringify(b),dataType:"json",success:function(a){d(a)}})}function queryGet(a,b,d){$.ajax({url:a,contentType:"application/json; charset\x3dUTF-8",type:"get",async:"undefined"===typeof d?!1:!0,dataType:"json",success:function(a){b(a)}})}
function queryPromise(a,b){return new Promise(function(d,e){$.ajax({url:a,contentType:"application/json; charset\x3dUTF-8",type:"post",data:JSON.stringify(b),dataType:"json",success:function(a){a.result&&d(a)}})})}
function queryPromiseWithAuth(a,b,d){return new Promise(function(e,c){$.ajax({url:a,contentType:"application/json; charset\x3dUTF-8",type:"post",data:JSON.stringify(b),beforeSend:function(a){a.setRequestHeader("Authorization","Bearer "+d)},dataType:"json",success:function(a){e(a)},error:function(a){c(a)}})})}
function cartPromise(a,b,d,e){return new Promise(function(c,g){$.ajax({url:a,contentType:"application/json; charset\x3dUTF-8",type:"post",data:JSON.stringify(b),dataType:"json",success:function(a){c(a);void 0!==a.resultMsg&&"00"!=a.resultMsg[0].code&&d&&($(".errorbox .gmg p").eq(0).text(a.resultMsg[0].message),$(".errorbox").bPopup({onClose:function(){void 0!==e&&""!=e&&(window.location.href=e)}}))},error:function(a){a.responseJSON&&"00"!=a.responseJSON.resultMsg[0].code&&d&&("98"==a.responseJSON.resultMsg[0].code?
$("#login").bPopup():($(".errorbox .gmg p").eq(0).text(a.responseJSON.resultMsg[0].message),$(".errorbox").bPopup({onClose:function(){void 0!==e&&""!=e&&(window.location.href=e)}})));g(a)}})})}function cartGetPromise(a){return new Promise(function(b,d){$.ajax({url:a,contentType:"application/json; charset\x3dUTF-8",type:"get",dataType:"json",success:function(a){b(a)},error:function(a){d(a)}})})}
function cartGetPromiseWithData(a,b){return new Promise(function(d,e){$.ajax({url:a,contentType:"application/json; charset\x3dUTF-8",type:"get",data:JSON.stringify(b),dataType:"json",success:function(a){d(a)},error:function(a){e(a)}})})}function queryAxios(a,b,d){return axios({method:d||"post",url:a,data:b})};
